### ISSUE TITLE
chore: implement unit-testing

### ISSUE THREAD

**Issue by AskeLange** [kinematic-lab/core#12]
## General information

Applies to all packages, as well as the plop templates.
Currently the most likely tool to be used is Jest.

Jest documentation: [See here](https://jestjs.io/docs/getting-started).

## Tasks

- [x] Implement for `@packages/utilities`
- [x] Add to plop templates
- [x] Include to CI-flow.
